title: My Blog
description: A personal blog built with Jekyll
author: Your Name
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evander0x.github.io" # the base hostname & protocol

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
