title: My Blog
description: A personal blog built with Jekyll
author: Evander
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evander0x.github.io" # the base hostname & protocol

# Build settings
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Display settings
show_excerpts: true
excerpt_separator: "<!--more-->"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
